D:\catiav5_r22\TestSpace2\.\CPPGeometryTools\CPPOpenNurbs.m\src
D:\catiav5_r22\TestSpace2\.\CPPGeometryTools\CPPOpenNurbs.m\LocalInterfaces
D:\catiav5_r22\TestSpace2\.\CPPGeometryTools\CPPOpenNurbs.m\LocalGenerated\win_b64
D:\catiav5_r22\TestSpace2\.\CPPGeometryTools\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ApplicationFrame\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ApplicationFrame\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ApplicationFrame\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ApplicationFrame\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\BSFBuildtimeData\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\BSFBuildtimeData\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSketcherUseItf\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATSketcherUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\DialogEngine\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\DialogEngine\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\DialogEngine\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\DraftingInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\DraftingInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\DraftingInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\DraftingInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectSpecsModeler\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectSpecsModeler\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectSpecsModeler\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectSpecsModeler\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\PartInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\PartInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\PartInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\PartInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SketcherInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SketcherInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SketcherInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\SketcherInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SketcherUI\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\SketcherUI\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\System\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\System\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\System\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\System\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\System\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\System\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\Visualization\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Visualization\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\Visualization\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\Visualization\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\VisualizationBase\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\VisualizationBase\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\VisualizationBase\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\AdvancedMathematics\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\AdvancedMathematics\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\AdvancedTopologicalOpe\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\AdvancedTopologicalOpe\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\AdvancedTopologicalOpeLight\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\AdvancedTopologicalOpeLight\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\AutomationInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\AutomationInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\AutomationInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\BasicTopologicalOpe\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\BasicTopologicalOpe\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\BasicTopologicalOpe\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\BatchInfrastructure\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\BatchInfrastructure\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\BatchInfrastructure\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\BatchInfrastructure\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CAT3DXmlInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CAT3DXmlInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CAT3DXmlInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CAT3DXmlInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATApplicationUIResources\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATAssemblyInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATAssemblyInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATAssemblyInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATAssemblyInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATCDS\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATCDS\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATCDSUtilities\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATCDSV5Driver\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATCDSV5Driver\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATCGMSkmDataItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATCloudBasicResources\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATCloudEditorInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATCloudEditorInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATDataCompatibilityInfra\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATDataCompatibilityInfra\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATElfiniOpenSoftware\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATFuzzyOperators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATGSMIDLItf\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATGSMIDLItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATGSMIDLItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATGSMModelServices\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATGSMOperatorsInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATGSMOperatorsInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATGSMTopoServices\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATGSMUseItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATGSMUseItf\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATGSMUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATGSMUseItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATGSOUseItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATGSOUseItf\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATGSOUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATGraphicProperties\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATGraphicProperties\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATIAApplicationFrame\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATIAApplicationFrame\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATIAApplicationFrame\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATIAApplicationFrame\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATIADataBasics\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATIADataBasics\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATIADataMacFortran\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATImmWtpInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATImmWtpInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATJavaBridge\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATJavaBridge\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATMecModExtendItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATMecModLiveUseItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATMecModLiveUseItf\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATMecModUseItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATMecModUseItf\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATPDMBaseInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATPDMBaseInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATPDMBaseInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATPDMBaseInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATPLMDictionary\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATPLMDictionary\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATPLMDictionary\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATShfInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATShfInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATShmInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATShmInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATSmarTeamIntegInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSmarTeamIntegInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATSmarTeamIntegInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSmarTeamIntegInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATSubdivisionApproximation\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSubdivisionMeshOperators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSubdivisionObjects\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSurfacicInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSurfacicInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATSurfacicManipulators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSurfacicOpeInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSurfacicResources\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSurfacicSharedItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSurfacicUIResources\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATSurfacicUIResources\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATTPSInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATTPSInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATTPSInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATTPSInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATTTRSInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATTTRSInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATTTRSInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATTechResultInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATTechResultInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATTechnologicalPackageUIItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATTechnologicalPackageUIItf\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATV4DataAdmin\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATV4System\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATV6V5Build\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATView\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATView\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATVirtualVaultSystem\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATVirtualVaultSystem\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CATWBx\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATXDocLinkInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CATXDocLinkInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CDMOperatorsInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CDMOperatorsInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CGMV5Interoperability\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CGMV5Interoperability\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\CGMV5SpecsQuery\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Communications\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Communications\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\Communications\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ComponentsCatalogsInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ComponentsCatalogsInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ComponentsCatalogsInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ComponentsCatalogsInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ConstraintModeler\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ConstraintModeler\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ConstraintModeler\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ConstraintModelerInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ConstraintModelerInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ConstraintModelerInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ConstraintModelerInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ConstraintModelerUI\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ConstraintModelerUI\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ConstraintSolver\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CurveBasedGeoOperators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CurveBasedInfrastructure\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CurveBasedMathematics\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\CurveBasedTopoOperators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\DCM2D\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\DCM3D\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\DMAPSInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\DMAPSInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\DMAPSInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\DMAPSInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\Dialog\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Dialog\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\FeatureCommands\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\FeatureCommands\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\FileMenu\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\FileMenu\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\FileMenu\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\FreeFormOperators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\FreeFormOperators\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\FreeStyleAnalysisInterface\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\FreeStyleAnalysisInterface\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\GMAdvancedOperatorsInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GMAdvancedOperatorsInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\GMModelInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GMModelInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\GMModelInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\GMOperatorsInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GMOperatorsInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\GSMInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GSMInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\GSMInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\GSMInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\GSMModel\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GSMModel\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\GSMModelPrivate\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GSOInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GSOInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\GSOInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\GenericNaming\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\GenericNaming\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GenericNaming\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\GeometricObjects\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GeometricObjects\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\GeometricObjects\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\GeometricObjects\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\GeometricObjectsCGM\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GeometricOperators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GeometricOperators\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\GeometryVisualization\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\GeometryVisualization\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\Graph\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Graph\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\HLRBase\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\InfInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\InfInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\InfInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\InfInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\Infra2DInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\InteractiveInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\InteractiveInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\InteractiveInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\InteractiveInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\KnowledgeInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\KnowledgeInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\KnowledgeInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\KnowledgeInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\KnowledgeModeler\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\KnowledgeModeler\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\LCCommon\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\LCCommon\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\LiteralFeatures\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\LiteralFeatures\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\LiteralFeatures\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\LiteralsEditor\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\LiteralsEditor\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\Mathematics\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Mathematics\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\Mathematics\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\MeasureGeometryInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\MeasureGeometryInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\MecModInterfaces\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\MecModInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\MecModInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\MecModInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\MecModInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\MecModLiveInterfaces\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\MecModLiveInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\MecModLiveInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\MecModLiveInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\MechanicalCommands\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\MechanicalCommands\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\MechanicalCommands\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\MechanicalModeler\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\MechanicalModeler\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\MechanicalModeler\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\MechanicalModeler\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\MechanicalModeler\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\MechanicalModelerLive\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\MechanicalModelerLive\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\MechanicalModelerLive\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\MechanicalModelerUI\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\MechanicalModelerUI\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\MechanicalModelerUI\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\MechanicalModelerUI\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\Multimedia\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Multimedia\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\Navigator2Interfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Navigator2Interfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\NavigatorInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\NavigatorInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\NavigatorInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\NavigatorInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\NewTopologicalObjects\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\NewTopologicalObjects\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\NewTopologicalObjects\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\NewTopologicalObjects\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerBase\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerBase\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerBase\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerBase\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerBase\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerBase\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerBaseUI\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerBaseUI\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerCATIA\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerCATIA\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerCATSDM\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerCATSDM\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerCollection\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerCollection\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerNavigator\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerNavigator\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerNavigator\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerNavigator\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerSDM\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerSDM\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerSDM\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerSystem\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerSystem\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerSystem\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ObjectModelerSystem\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\PolygonalTools\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\PolyhedralInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\PolyhedralInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\PolyhedralMathematics\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\PolyhedralObjects\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\PolyhedralOperators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\PolyhedralVisuOperators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\PolyhedralVisualization\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Print\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Print\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\Print\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\PrintBase\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\PrintBase\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\PrintBase\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\PrintBase\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ProductStructure\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ProductStructure\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ProductStructure\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ProductStructure\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ProductStructureInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\ProductStructureInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\ProductStructureInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\ProductStructureInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SDMBinaryForm\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SDMRuntime\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SDMRuntime\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\SDMSTEPForm\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SGMOperatorsInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SIMInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SIMInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SIMInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\SIMInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SimulationInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SimulationInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SimulationInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\SimulationInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SketcherModeler\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SketcherToolsUI\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SketcherToolsUI\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SketcherToolsUI\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\SketcherVisu\PrivateInterfaces
C:\Program Files\Dassault Systemes\B22\.\SketcherVisu\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SketcherVisu\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SketcherVisu\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SpaceAnalysisInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SpaceAnalysisInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SpaceAnalysisInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\SpaceAnalysisInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\SpecialAPI\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SpecialAPI\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\SurfacicGeoOperators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SurfacicInfrastructure\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SurfacicMathematics\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\SurfacicTopoOperators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Tessellation\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\Tessellation\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\TopologicalOperators\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\TopologicalOperators\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\TopologicalOperatorsLight\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\TopologicalOperatorsLight\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\VBA\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\VBA\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\XMLParser\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B22\.\XMLParser\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\XMLParser\PublicInterfaces
C:\Program Files\Dassault Systemes\B22\.\XMLParser\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B22\.\XlatorCGM\ProtectedInterfaces
